### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by ghost** [jeehoonkang/membarrier-rs#2]
Windows has `FlushProcessWriteBuffers`, which is similar to `sys_membarrier`: https://github.com/dotnet/coreclr/pull/1057

**Comment by jeehoonkang** [comment]
Thanks for your suggestion!

I added windows support: https://github.com/jeehoonkang/membarrier-rs/commit/6a0a4c665d69e3be274c6eb5e643ba676b803a90
But I couldn't test it because I don't have a Windows machine.  I'll test it later and then close this issue.

**Comment by ghost** [comment]
Perhaps you don't even need one :) You could take an AppVeyor config from [japaric/trust](https://github.com/japaric/trust) to add continuous integration on Windows.
