### ISSUE TITLE
Use winapi crate instead of kernel32-sys

### ISSUE THREAD

**Issue by atouchet** [jeehoonkang/membarrier-rs#21]
kernel32-sys is no longer used with winapi 0.3: https://github.com/retep998/winapi-rs#should-i-still-use-those--sys-crates-such-as-kernel32-sys

**Comment by jeehoonkang** [comment]
Thanks for the report! I think I don't have enough bandwidth to address this issue myself, but I'm happy to accept PRs.

**Comment by atouchet** [comment]
Another option would be to switch to using windows/windows-sys: https://github.com/microsoft/windows-rs
