### ISSUE TITLE
Abort instead of panic

### ISSUE THREAD

**Issue by ghost** [jeehoonkang/membarrier-rs#7]
Calling `panic!()` when a syscall fails seems risky. We should probably call `libc::abort()` instead.

**Comment by jeehoonkang** [comment]
I just wonder---are there precedence of choosing `abort()` over `panic!()` or more detailed discussion on the choice?  I'd just like to know what risks `panic!()` can have in this case.

**Comment by ghost** [comment]
To be honest, I'm not sure. This is just a case where it *feels wrong* to panic.

The way I see it, there are two kinds of errors where we panic/abort:

* Logic errors, e.g. used an out-of-bounds index or called `.unwrap()` on a `None` value.
* Fatal errors, e.g. allocation failed (the system went out of memory), or the ref counter in `Rc` has overflowed.

The former class of errors is more common and more benign. It's okay to unwind the stack and call destructors in order to clean up the application state.

The latter class of errors is more rare and more serious in the sense that we're not really sure if trying to clean up the state is worthwhile at all. More importantly, the cleanup might cascade into even more serious errors so we better stop right now and abort.

The kind of system call errors we have here seems like it would fall into the latter class of errors. I'm not 100% sure how safe it is to unwind (maybe it is, but not sure) so my instinct is to tread carefully and abort.

**Comment by jeehoonkang** [comment]
Your argument is convincing.  Let's `abort()` rather than `panic!()`.

051cc1107ea8720d06a0842146aa7cd6ed93e667 resolved this issue.
